---
name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # this is just the host, but the job will run in the container
    container: ubuntu:20.04
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        # Install required dependencies inside the container
        apt-get update
        apt-get install -y python3 python3-pip python3-dev wget build-essential      
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create distribution binary
      run: pyinstaller -F router_upgrade_bootstrap.py --runtime-tmpdir /opt/netfoundry/
    - name: Use pyinstall to create main binary
      run: mkdir /opt/netfoundry; pyinstaller -F router_upgrade.py --runtime-tmpdir /opt/netfoundry/
    - name: version
      run: echo "version=$(./dist/router_upgrade -v)" >> $GITHUB_ENV
      id: version

    - name: Tar bootstrap
      # tar with previous distibuted name for backwards compatibility
      run: cd dist; mv router_upgrade_bootstrap zt-upgrade; tar -zcvf router_upgrade_bootstrap.tar.gz zt-upgrade
    - name: Tar main script
      # tar with previous distibuted name for backwards compatibility
      run: cd dist; mv router_upgrade .router_upgrade; tar -zcvf router_upgrade.tar.gz .router_upgrade 

    - name: release
      uses: ncipollo/release-action@v1
      id: release
      with:
        draft: false
        prerelease: false
        tag: v${{ env.version }}
        artifacts: "dist/router_upgrade_bootstrap.tar.gz,dist/router_upgrade.tar.gz"
        artifactContentType: application/gzip
      env:
        GITHUB_TOKEN: ${{ github.token }}

